<?php

$form = $this->form;

$this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">×</button>')
    ->setMessageCloseString('</div>')
    ->render($form);

if ($this->duplicate) {
	echo '<div class="alert alert-error">'.$this->duplicate.'<button type="button" class="close" data-dismiss="alert">×</button></div>';
}
    

$form->setAttribute('action', 
			$this->url('produto/default', 
						array('controller' => 'produto', 'action' => 'add'))
			);

$form->prepare();
echo $this->form()->openTag ($form);
echo $this->formCollection ($form);
echo $this->form()->closeTag ();



