<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Zenders - '. $this->translate('ZF2openStore'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css');

        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap-inputmask.min.js'); ?>

    </head>
    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">
                        <?php echo $this->translate('ZF2OpenStore') ?>
                    </a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>">
                                <?php echo $this->translate('Home') ?></a></li>
                            <li class="active dropdown">
                                <a href="<?php echo $this->url('home') ?>" class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->translate('Produtos') ?><span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/produto/add">Adicionar novos produtos</a></li>
                                    <li><a href="/produto">Listar produtos</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>


        <div class="container-fluid">
                
                    <div class="page-header">
                        <h1><?php echo $this->layout()->pageHeader; ?> 
                            <?php echo (!empty($this->layout()->subPageHeader)) ? '<small>('. $this->layout()->subPageHeader .')</small>' : '<small></small>'; ?>
                        </h1>
                    </div>
                    <?php echo $this->content; ?>
                

            <div class="clearFix"></div>

            <footer>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
